### ISSUE TITLE
Can I PR my own if I think it's awesome?

### ISSUE THREAD

**Issue by MicroDroid** [iRaul/creative-portfolios#28]

**Comment by MicroDroid** [comment]
I do understand that. But how do I know if my portfolio, for example, is creative?

I just made a weird kind of a portfolio that is drastically different than most portfolios (not that's it's super awesome though), I'm wondering if that'd fit here. (fit here because it's creative, not because it's mine)

**Comment by imisterk** [comment]
It would be nice to have a section on the official website for "Candidates" where public could potentially vote for new listings to the sections. If approved, your portfolio gets listed together with contact information (social media, etc).

http://www.creative-portfolios.com has potential! **PS**: It needs an SSL added.

**Comment by TheJaredWilcurt** [comment]
If it is this:

* https://microdroid.github.io

Then I would say no. That does not meet the criteria of `awesome-portfolios`

**Comment by MicroDroid** [comment]
@TheJaredWilcurt oof how did you even notice this, I just pushed it a few hours ago.

Anyways that's fine but I still upvote @imisterk's idea, it'd be nice to have a system where people can suggest portfolios to be added. I'll keep this open for that unless it's not planned.

**Comment by Cryptoxygen** [comment]
Portfolio is important for any organization, A portfolio is a living and changing collection of records that reflect your accomplishments, skills, experiences, and attributes.
