### ISSUE TITLE
new portfolio

### ISSUE THREAD

**Issue by joshternyak** [iRaul/creative-portfolios#48]
Josh Ternyak
https://joshternyak.com

**Comment by auriga-z** [comment]
Abhishek Jha
https://abhishekjha.me/
FWA: https://thefwa.com/cases/abhishek-jhas-portfolio-2020-p2

**Comment by ashley-howard** [comment]
Ashley Howard
https://ashley.how

**Comment by iRaul** [comment]
Please follow this [Contribution Guide](https://github.com/iRaul/creative-portfolios/blob/master/contributing.md) 🙂
